"""Verify a claim before reporting it: does EduVidQA's transcript already contain the reference answer?

The gate found that frames do not improve answers on EduVidQA's synthetic training questions. The
paper says these questions were generated by GPT-4o from NPTEL transcripts (Sec. 3.2). Instead of
assuming the consequence, this measures it with the paper's own FactQA judge prompt:

    support(own)      share of the REFERENCE answer's claims supported by the transcript excerpt
                      (+-120 s) that the answerer was given
    support(control)  the same reference against the excerpt of a question from a DIFFERENT video
                      (how much support appears by chance, e.g. generic CS statements)

English-transcript gate questions only. Free NVIDIA NIM judge; 100-call ledger.

    python scripts/v3_verify_transcript_support.py
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import numpy as np

from videoqa.packing import format_excerpt
from videoqa.v2.budget import CallBudget
from videoqa.v3.factqa import OpenAICompatFactQA

RUN = Path("runs/v3_gate")


def main() -> None:
    spec = importlib.util.spec_from_file_location("gate", Path(__file__).with_name("v3_gate_frames.py"))
    g = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(g)
    english = g._english_videos()
    scored = {json.loads(x)["qa_id"] for x in Path("reports/v3_gate/scores_nemotron-ultra_T-R1-C4.jsonl").read_text().splitlines() if x}
    rows = [r for r in g._question_rows() if r["qa_id"] in scored and r["video_id"] in english]
    rows.sort(key=lambda r: hashlib.sha256(r["qa_id"].encode()).hexdigest())
    excerpts = {r["qa_id"]: format_excerpt(g._excerpt(r)) for r in rows}
    # Control: the excerpt of the next question in a fixed order that comes from a different video.
    control = {}
    for i, r in enumerate(rows):
        other = next(o for o in rows[i + 1:] + rows[:i] if o["video_id"] != r["video_id"])
        control[r["qa_id"]] = excerpts[other["qa_id"]]
    budget = CallBudget(RUN / "budget_verify_transcript.json", 100, 3600.0)
    judge = OpenAICompatFactQA("nvidia/nemotron-3-ultra-550b-a55b", RUN / "factqa_verify_transcript.jsonl",
                               budget=budget, min_interval_s=1.6)
    judge.time_share = 1 / 4

    def run(job):
        r, which, text = job
        try:
            v = judge.claims(r["qa_id"], f"support_{which}", r["question"], r["gold_answer"], text)
            return r["qa_id"], which, v["score"]
        except (RuntimeError, OSError) as e:
            print(f"{r['qa_id']} {which}: judge failed ({str(e)[:60]})", flush=True)
            return r["qa_id"], which, None

    jobs = [(r, "own", excerpts[r["qa_id"]]) for r in rows] + [(r, "control", control[r["qa_id"]]) for r in rows]
    with ThreadPoolExecutor(max_workers=4) as pool:
        res = list(pool.map(run, jobs))
    by = {}
    for q, which, s in res:
        by.setdefault(q, {})[which] = s
    pairs = {q: d for q, d in by.items() if d.get("own") is not None and d.get("control") is not None}
    own = np.array([d["own"] for d in pairs.values()])
    ctl = np.array([d["control"] for d in pairs.values()])
    out = {"questions": len(pairs), "videos": len({r["video_id"] for r in rows if r["qa_id"] in pairs}),
           "judge": "nvidia/nemotron-3-ultra-550b-a55b", "judge_calls": budget.calls,
           "reference_claims_supported_by_own_transcript": float(own.mean()),
           "reference_claims_supported_by_other_video_transcript": float(ctl.mean()),
           "share_of_questions_own_support_at_least_0.5": float((own >= 0.5).mean()),
           "share_of_questions_own_support_at_least_0.8": float((own >= 0.8).mean()),
           "own_minus_control": float((own - ctl).mean())}
    Path("reports/v3_gate/transcript_support.json").write_text(json.dumps(out, indent=1), encoding="utf-8")
    print(json.dumps(out, indent=1))


if __name__ == "__main__":
    main()
