"""A deterministic synthetic 'lecture' video used by tests and the CPU smoke run.

It is a REAL mp4 file (encoded with PyAV) with a matching timed transcript and
three questions that exercise the research idea:

    q_lr      "What learning rate was used?"          spoken AND on a slide
              -> under TARGETED damage the speech is gone, so looking helps.
    q_acc     "What final accuracy is shown?"          visible ONLY (never spoken)
              -> the required "known visual-only fact" integration test.
    q_switch  "What colour does the indicator turn?"   before/after change
              -> the required "before/after change" integration test.

The slide schedule is also exposed as ground truth (``SLIDES``) so a test-double
answerer can "read" a frame by its timestamp.  That double exists only to test
plumbing; it is never used for research results.
"""

from __future__ import annotations

import dataclasses
from fractions import Fraction
from pathlib import Path

import av
import numpy as np
from PIL import Image, ImageDraw, ImageFont

from .schemas import QAItem, Transcript, TranscriptSegment

WIDTH, HEIGHT, FPS = 640, 360, 5
DURATION_S = 90.0


@dataclasses.dataclass(frozen=True)
class Slide:
    start_s: float
    end_s: float
    title: str
    body: str
    indicator: str | None = None   # "red" / "green" circle, for the before/after fact


# Ground-truth visual schedule.  Note slide 3 states "87%" which is never spoken.
SLIDES: tuple[Slide, ...] = (
    Slide(0, 15, "Lecture 3", "Optimisation basics"),
    Slide(15, 30, "Setup", "Learning rate = 0.3"),
    Slide(30, 45, "Results", "Final accuracy: 87%"),
    Slide(45, 55, "Circuit demo", "Switch OFF", indicator="red"),
    Slide(55, 65, "Circuit demo", "Switch ON", indicator="green"),
    Slide(65, 90, "Summary", "Questions?"),
)

# Timed speech.  The accuracy number is deliberately NOT spoken.
SPEECH: tuple[tuple[float, float, str], ...] = (
    (1.0, 6.0, "welcome to lecture three on optimisation"),
    (7.0, 13.0, "today we look at how training behaves"),
    (16.0, 22.0, "for this run the learning rate was set to 0.3"),
    (23.0, 29.0, "we kept every other setting the same"),
    (31.0, 37.0, "here are the results of the experiment"),
    (38.0, 44.0, "as you can see it worked quite well"),
    (46.0, 52.0, "now a small circuit demonstration"),
    (56.0, 62.0, "watch what happens to the indicator light"),
    (66.0, 72.0, "to summarise we covered optimisation settings"),
    (74.0, 80.0, "please send me any questions by email"),
    (82.0, 88.0, "see you next week"),
)


def slide_at(t: float) -> Slide:
    for s in SLIDES:
        if s.start_s <= t < s.end_s:
            return s
    return SLIDES[-1]


def render_slide(slide: Slide) -> Image.Image:
    """Draw a simple slide: title, body text and an optional coloured indicator."""
    img = Image.new("RGB", (WIDTH, HEIGHT), (245, 245, 240))
    draw = ImageDraw.Draw(img)
    title_font = ImageFont.load_default(size=34)
    body_font = ImageFont.load_default(size=40)
    draw.rectangle([0, 0, WIDTH, 60], fill=(30, 60, 110))
    draw.text((20, 12), slide.title, fill=(255, 255, 255), font=title_font)
    draw.text((40, 150), slide.body, fill=(20, 20, 20), font=body_font)
    if slide.indicator:
        colour = (210, 40, 40) if slide.indicator == "red" else (40, 170, 60)
        draw.ellipse([500, 230, 580, 310], fill=colour)
    return img


def write_video(path: str | Path) -> Path:
    """Encode the lecture to ``path`` (H.264, 5 fps).  Deterministic output."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    cache: dict[Slide, np.ndarray] = {}
    with av.open(str(path), mode="w") as container:
        stream = container.add_stream("libx264", rate=Fraction(FPS, 1))
        stream.width, stream.height, stream.pix_fmt = WIDTH, HEIGHT, "yuv420p"
        stream.options = {"crf": "23", "preset": "veryfast"}
        for i in range(int(DURATION_S * FPS)):
            slide = slide_at(i / FPS)
            if slide not in cache:
                cache[slide] = np.asarray(render_slide(slide))
            frame = av.VideoFrame.from_ndarray(cache[slide], format="rgb24")
            for packet in stream.encode(frame):
                container.mux(packet)
        for packet in stream.encode():  # flush
            container.mux(packet)
    return path


def transcript(video_id: str = "fixture_lecture") -> Transcript:
    segs = [TranscriptSegment(id=f"s{i:05d}", start_s=a, end_s=b, text=t) for i, (a, b, t) in enumerate(SPEECH)]
    return Transcript(video_id=video_id, segments=segs, source="fixture")


def qa_items(video_id: str = "fixture_lecture") -> list[QAItem]:
    common = dict(video_id=video_id, source_dataset="fixture", source_split="train",
                  provenance_and_license="synthetic, generated by videoqa.fixtures (no third-party content)")
    return [
        QAItem(qa_id="q_lr", question="What learning rate was used for this run?", gold_answer="0.3",
               options=["0.01", "0.1", "0.3", "1.0"], gold_option_index=2,
               evidence_intervals_s=[(15.0, 30.0)], **common),
        QAItem(qa_id="q_acc", question="What final accuracy is shown on the results slide?", gold_answer="87%",
               options=["67%", "77%", "87%", "97%"], gold_option_index=2,
               evidence_intervals_s=[(30.0, 45.0)], **common),
        QAItem(qa_id="q_switch", question="What colour does the indicator light turn to in the circuit demo?",
               gold_answer="green", options=["red", "green", "blue", "yellow"], gold_option_index=1,
               evidence_intervals_s=[(45.0, 65.0)], **common),
    ]
